### ISSUE TITLE
How can I remove an external share recipient from the folder

### ISSUE THREAD

**Issue by arjun1311** [ctera/ctera-python-sdk#168]
I tried to share the folder to an external user like this:-
```
jsmith = portal_types.ShareRecipient.external('jsmith@hotmail.com', True).expire_in(5).read_only())
file_browser.share('My Files/Projects/2020/ProjectX', [jsmith])
```
but now the problem is how can I remove jsmith user from the folder, in the documentation  `CloudDrive.remove_share_recipients(path, accounts)` - takes a List of `[cterasdk.core.types.PortalAccount]` object, I belive this is for ctera internal user, not the external user.

How can I remove an external user from the shared folder?

**Comment by saimonation** [comment]
Hey @arjun1311, `remove_share_recipients` also accepts email addresses. This would work:

`file_browser.remove_share_recipients("path/to/file/or/folder", ["name@domain.com"])`

**Comment by arjun1311** [comment]
Thanks, I got it now. 

One more question Let's say If I share my folder with **jsmith**(above user), the sharable link will be shared on the mail and I believe it will be different for every user. 

can I get that link from the code not from the mail?

**Comment by arjun1311** [comment]
Nope, I need to send that unique link from the code, I have built an api, I am passing the email and then I need to return the unique link from the api.

**Comment by saimonation** [comment]
Understood. The only other alternative would be to generate a public link (not unique per user) which returns a link as part of the response: https://ctera-python-sdk.readthedocs.io/en/latest/user_guides/Portal/FileBrowser.html#create-public-link
