### ISSUE TITLE
Can I add username from publiclink

### ISSUE THREAD

**Issue by arjun1311** [ctera/ctera-python-sdk#173]
Hello,

I shared a publiclink of a folder with someone who already have the ctera account, but when he uploaded the file, it is showing to me as **guest**, like shown in the below image. I tried with collaboration share too, but that won't generate any link.

I just want to know how can I add username or any name to it, so it shows who uploaded the file.

![image](https://user-images.githubusercontent.com/28755144/218759745-539bf687-4013-4a94-98e8-e7a0d6c62ed1.png)

**Comment by saimonation** [comment]
@arjun1311, this behavior should not occur when using collaboration shares. if the recipient is a team member, the correct username is presented via the web-interface. the *guest* user shows when read-write recipients make changes using a public link. Can you try to reproduce this? 
Closing this issue as this pertains to a product behavior, and not a function of the CTERA Python SDK.
