### ISSUE TITLE
edge filer delete function requires 'localFiles' before the actual path

### ISSUE THREAD

**Issue by ronier83** [ctera/ctera-python-sdk#188]
we found an issue when trying to delete a folder from path:
'cloud/users/sdf sdf/My Files/testSDK'
using:
file_browser = filer.files
file_browser.delete('cloud/users/sdf sdf/My Files/testSDK')
from capturing the network it seems the path is actually
file_browser.delete('localFiles/cloud/users/sdf sdf/My Files/testSDK')

**Comment by saimonation** [comment]
@ronier83: fixed. 
https://github.com/ctera/ctera-python-sdk/pull/197
